/*Even Fibonacci numbers
Problem 2 

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

/******************************************************************************

                            Online C Compiler.
                Code, Compile, Run and Debug C program online.
Write your code in this editor and press "Run" button to compile and execute it.

*******************************************************************************/

#include <stdio.h>

int main()
{
    int first  = 0;
    int second = 1;
    int urmatorul;
    int c;
    double suma = 0;
    for( c = 0 ; c < 32 ; c++)
    {
        
     
            urmatorul = first + second;
            first = second;
            second = urmatorul;
            
         
        
        if(( urmatorul % 2 == 0) && (urmatorul < (4000000)))
        {
        suma = suma + urmatorul;
        
     //   printf("\n   urmatorul %d :",urmatorul);
        }
        
       // printf("\n%d", urmatorul);
    }
    
    printf("\n%lf",suma);


}
